version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    cooldown:
      default-days: 7
    groups:
      production:
        applies-to: version-updates
        patterns:
          - "jaxtyping"
          - "torch"
          - "torchaudio"
          - "numpy"
          - "scipy"

      documentation:
        applies-to: version-updates
        patterns:
          - "Sphinx*"
          - "sphinx*"
          - "myst*"
          - "torchmetrics"
          - "lightning"
          - "rich"
          - "gwpy"
          - "jupyter"

      development:
        applies-to: version-updates
        patterns: ["*"]
        exclude-patterns:
          - "jaxtyping"
          - "torch"
          - "torchaudio"
          - "numpy"
          - "scipy"
          - "Sphinx*"
          - "sphinx*"
          - "myst*"
          - "torchmetrics"
          - "lightning"
          - "rich"
          - "gwpy"
          - "jupyter"

      security:
        applies-to: security-updates
        patterns: ["*"]
