version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"

    cooldown:
      default-days: 7

    groups:
      production:
        dependency-type: "production"
      development:
        dependency-type: "development"
        exclude-patterns:
          - "Sphinx"
          - "sphinx*"
          - "myst*"
          - "torchmetrics"
          - "lightning"
          - "rich"
          - "gwpy"
          - "jupyter"
      documentation:
        patterns:
          - "Sphinx"
          - "sphinx*"
          - "myst*"
          - "torchmetrics"
          - "lightning"
          - "rich"
          - "gwpy"
          - "jupyter"

    versioning-strategy: increase-if-necessary
