import lal
import lalsimulation
import numpy as np
import pytest
import torch
from astropy import units as u
from torch.distributions import Uniform

import ml4gw.waveforms as waveforms
from ml4gw.waveforms.conversion import (
    bilby_spins_to_lalsim,
    chirp_mass_and_mass_ratio_to_components,
)


@pytest.fixture(params=[256, 1024, 2048])
def sample_rate(request):
    return request.param


@pytest.fixture()
def chirp_mass(request):
    dist = Uniform(5, 100)
    return dist.sample((1000,))


@pytest.fixture()
def mass_ratio():
    dist = Uniform(0.125, 0.99)
    return dist.sample((1000,))


@pytest.fixture()
def a_1(request):
    dist = Uniform(0, 0.90)
    return dist.sample((1000,))


@pytest.fixture()
def a_2(request):
    dist = Uniform(0, 0.90)
    return dist.sample((1000,))


@pytest.fixture()
def tilt_1(request):
    dist = Uniform(0, torch.pi)
    return dist.sample((1000,))


@pytest.fixture()
def tilt_2(request):
    dist = Uniform(0, torch.pi)
    return dist.sample((1000,))


@pytest.fixture()
def phi_12(request):
    dist = Uniform(0, 2 * torch.pi)
    return dist.sample((1000,))


@pytest.fixture()
def phi_jl(request):
    dist = Uniform(0, 2 * torch.pi)
    return dist.sample((1000,))


@pytest.fixture()
def distance(request):
    dist = Uniform(100, 3000)
    return dist.sample((1000,))


@pytest.fixture()
def theta_jn(request):
    dist = Uniform(0, torch.pi)
    return dist.sample((1000,))


@pytest.fixture()
def phase(request):
    dist = Uniform(0, 2 * torch.pi)
    return dist.sample((1000,))


@pytest.fixture()
def chi_1(request):
    dist = Uniform(-0.999, 0.999)
    return dist.sample((1000,))


@pytest.fixture()
def chi_2(request):
    dist = Uniform(-0.999, 0.999)
    return dist.sample((1000,))


@pytest.fixture(params=[20, 40])
def f_ref(request):
    return request.param


def test_taylor_f2(
    chirp_mass,
    mass_ratio,
    chi_1,
    chi_2,
    phase,
    distance,
    f_ref,
    theta_jn,
    sample_rate,
):
    mass_1, mass_2 = chirp_mass_and_mass_ratio_to_components(
        chirp_mass, mass_ratio
    )

    # compare each waveform with lalsimulation
    for i in range(len(chirp_mass)):

        # construct lalinference params
        params = dict(
            m1=mass_1[i].item() * lal.MSUN_SI,
            m2=mass_2[i].item() * lal.MSUN_SI,
            S1x=0,
            S1y=0,
            S1z=chi_1[i].item(),
            S2x=0,
            S2y=0,
            S2z=chi_2[i].item(),
            distance=(distance[i].item() * u.Mpc).to("m").value,
            inclination=theta_jn[i].item(),
            phiRef=phase[i].item(),
            longAscNodes=0.0,
            eccentricity=0.0,
            meanPerAno=0.0,
            deltaF=1.0 / sample_rate,
            f_min=20,
            f_ref=f_ref,
            f_max=300,
            approximant=lalsimulation.TaylorF2,
            LALpars=lal.CreateDict(),
        )
        hp_lal, hc_lal = lalsimulation.SimInspiralChooseFDWaveform(**params)

        # reconstruct frequencies generated by
        # lal and filter based on fmin and fmax
        lal_freqs = np.array(
            [
                hp_lal.f0 + ii * hp_lal.deltaF
                for ii in range(len(hp_lal.data.data))
            ]
        )

        lal_mask = (lal_freqs > params["f_min"]) & (
            lal_freqs < params["f_max"]
        )

        lal_freqs = lal_freqs[lal_mask]
        torch_freqs = torch.tensor(lal_freqs, dtype=torch.float64)

        # generate waveforms using ml4gw
        hc_ml4gw, hp_ml4gw = waveforms.TaylorF2()(
            torch_freqs,
            chirp_mass[i][None],
            mass_ratio[i][None],
            chi_1[i][None],
            chi_2[i][None],
            distance[i][None],
            phase[i][None],
            theta_jn[i][None],
            f_ref,
        )

        hc_ml4gw = hc_ml4gw[0]
        hp_ml4gw = hp_ml4gw[0]

        hp_lal_data = hp_lal.data.data[lal_mask]
        hc_lal_data = hc_lal.data.data[lal_mask]

        # ensure no nans
        assert not torch.any(torch.isnan(hc_ml4gw))
        assert not torch.any(torch.isnan(hp_ml4gw))

        assert np.allclose(
            1e21 * hp_lal_data.real, 1e21 * hp_ml4gw.real.numpy(), atol=1e-3
        )
        assert np.allclose(
            1e21 * hp_lal_data.imag, 1e21 * hp_ml4gw.imag.numpy(), atol=1e-3
        )
        assert np.allclose(
            1e21 * hc_lal_data.real, 1e21 * hc_ml4gw.real.numpy(), atol=1e-3
        )
        assert np.allclose(
            1e21 * hc_lal_data.imag, 1e21 * hc_ml4gw.imag.numpy(), atol=1e-3
        )

        # taylor f2 is symmetric w.r.t m1 --> m2 flip.
        # so test that the waveforms are the same when m1 and m2
        # (and corresponding chi_1, chi_2 are flipped)
        # are flipped this can be done by flipping mass ratio
        hc_ml4gw, hp_ml4gw = waveforms.TaylorF2()(
            torch_freqs,
            chirp_mass[i][None],
            1 / mass_ratio[i][None],
            chi_2[i][None],
            chi_1[i][None],
            distance[i][None],
            phase[i][None],
            theta_jn[i][None],
            f_ref,
        )

        hc_ml4gw = hc_ml4gw[0]
        hp_ml4gw = hp_ml4gw[0]

        assert np.allclose(
            1e21 * hp_lal_data.real, 1e21 * hp_ml4gw.real.numpy(), atol=1e-3
        )
        assert np.allclose(
            1e21 * hp_lal_data.imag, 1e21 * hp_ml4gw.imag.numpy(), atol=1e-3
        )
        assert np.allclose(
            1e21 * hc_lal_data.real, 1e21 * hc_ml4gw.real.numpy(), atol=1e-3
        )
        assert np.allclose(
            1e21 * hc_lal_data.imag, 1e21 * hc_ml4gw.imag.numpy(), atol=1e-3
        )


def test_phenom_d(
    chirp_mass,
    mass_ratio,
    chi_1,
    chi_2,
    distance,
    phase,
    theta_jn,
    sample_rate,
    f_ref,
):
    mass_1, mass_2 = chirp_mass_and_mass_ratio_to_components(
        chirp_mass, mass_ratio
    )

    # compare each waveform with lalsimulation
    for i in range(len(chirp_mass)):

        # construct lalinference params
        params = dict(
            m1=mass_1[i].item() * lal.MSUN_SI,
            m2=mass_2[i].item() * lal.MSUN_SI,
            S1x=0,
            S1y=0,
            S1z=chi_1[i].item(),
            S2x=0,
            S2y=0,
            S2z=chi_2[i].item(),
            distance=(distance[i].item() * u.Mpc).to("m").value,
            inclination=theta_jn[i].item(),
            phiRef=phase[i].item(),
            longAscNodes=0.0,
            eccentricity=0.0,
            meanPerAno=0.0,
            deltaF=1.0 / sample_rate,
            f_min=20,
            f_ref=f_ref,
            f_max=300,
            approximant=lalsimulation.IMRPhenomD,
            LALpars=lal.CreateDict(),
        )
        hp_lal, hc_lal = lalsimulation.SimInspiralChooseFDWaveform(**params)

        # reconstruct frequencies generated by
        #  lal and filter based on fmin and fmax
        lal_freqs = np.array(
            [
                hp_lal.f0 + ii * hp_lal.deltaF
                for ii in range(len(hp_lal.data.data))
            ]
        )

        lal_mask = (lal_freqs > params["f_min"]) & (
            lal_freqs < params["f_max"]
        )

        lal_freqs = lal_freqs[lal_mask]
        torch_freqs = torch.tensor(lal_freqs, dtype=torch.float32)

        # generate waveforms using ml4gw
        hc_ml4gw, hp_ml4gw = waveforms.IMRPhenomD()(
            torch_freqs,
            chirp_mass[i][None],
            mass_ratio[i][None],
            chi_1[i][None],
            chi_2[i][None],
            distance[i][None],
            phase[i][None],
            theta_jn[i][None],
            f_ref,
        )

        hc_ml4gw = hc_ml4gw[0]
        hp_ml4gw = hp_ml4gw[0]

        hp_lal_data = hp_lal.data.data[lal_mask]
        hc_lal_data = hc_lal.data.data[lal_mask]

        assert not torch.any(torch.isnan(hc_ml4gw))
        assert not torch.any(torch.isnan(hp_ml4gw))

        assert np.allclose(
            1e21 * hp_lal_data.real, 1e21 * hp_ml4gw.real.numpy(), atol=1e-3
        )
        assert np.allclose(
            1e21 * hp_lal_data.imag, 1e21 * hp_ml4gw.imag.numpy(), atol=1e-3
        )
        assert np.allclose(
            1e21 * hc_lal_data.real, 1e21 * hc_ml4gw.real.numpy(), atol=1e-3
        )
        assert np.allclose(
            1e21 * hc_lal_data.imag, 1e21 * hc_ml4gw.imag.numpy(), atol=1e-3
        )


def test_phenom_p(
    chirp_mass,
    mass_ratio,
    tilt_1,
    tilt_2,
    a_1,
    a_2,
    theta_jn,
    phase,
    distance,
    phi_jl,
    phi_12,
    sample_rate,
    f_ref,
):
    # m1 > m2
    mass_1, mass_2 = chirp_mass_and_mass_ratio_to_components(
        chirp_mass, mass_ratio
    )

    inclination, s1x, s1y, s1z, s2x, s2y, s2z = bilby_spins_to_lalsim(
        theta_jn,
        phi_jl,
        tilt_1,
        tilt_2,
        phi_12,
        a_1,
        a_2,
        mass_1,
        mass_2,
        f_ref,
        phase,
    )

    # compare each waveform with lalsimulation
    for i in range(2):  # (len(chirp_mass)):
        print(i, mass_ratio)
        # construct lalinference params
        params = dict(
            m1=mass_1[i].item() * lal.MSUN_SI,
            m2=mass_2[i].item() * lal.MSUN_SI,
            S1x=s1x[i].item(),
            S1y=s1y[i].item(),
            S1z=s1z[i].item(),
            S2x=s2x[i].item(),
            S2y=s2y[i].item(),
            S2z=s2z[i].item(),
            distance=(distance[i].item() * u.Mpc).to("m").value,
            inclination=inclination[i].item(),
            phiRef=phase[i].item(),
            longAscNodes=0.0,
            eccentricity=0.0,
            meanPerAno=0.0,
            deltaF=1.0 / sample_rate,
            f_min=20,
            f_ref=f_ref,
            f_max=300,
            approximant=lalsimulation.IMRPhenomPv2,
            LALpars=lal.CreateDict(),
        )
        hp_lal, hc_lal = lalsimulation.SimInspiralChooseFDWaveform(**params)

        # reconstruct frequencies generated by
        # lal and filter based on fmin and fmax
        lal_freqs = np.array(
            [
                hp_lal.f0 + ii * hp_lal.deltaF
                for ii in range(len(hp_lal.data.data))
            ]
        )

        lal_mask = (lal_freqs > params["f_min"]) & (
            lal_freqs < params["f_max"]
        )

        lal_freqs = lal_freqs[lal_mask]
        torch_freqs = torch.tensor(lal_freqs, dtype=torch.float32)

        # generate waveforms using ml4gw
        hc_ml4gw, hp_ml4gw = waveforms.IMRPhenomPv2()(
            torch_freqs,
            chirp_mass[i][None],
            mass_ratio[i][None],
            s1x[i][None],
            s1y[i][None],
            s1z[i][None],
            s2x[i][None],
            s2y[i][None],
            s2z[i][None],
            distance[i][None],
            phase[i][None],
            inclination[i][None],
            f_ref,
        )

        hc_ml4gw = hc_ml4gw[0]
        hp_ml4gw = hp_ml4gw[0]

        hp_lal_data = hp_lal.data.data[lal_mask]
        hc_lal_data = hc_lal.data.data[lal_mask]

        np.savetxt("lal_hp.txt", hp_lal_data.real)
        np.savetxt("ml4gw_hp.txt", hp_ml4gw.real.numpy())

        np.savetxt("lal_hp_imag.txt", hp_lal_data.imag)
        np.savetxt("ml4gw_hp_imag.txt", hp_ml4gw.imag.numpy())

        print(
            i,
            s1x[i],
            s1y[i],
            s1z[i],
            s2x[i],
            s2y[i],
            s2z[i],
            inclination[i],
            phase[i],
        )

        assert np.allclose(
            1e21 * hp_lal_data.real, 1e21 * hp_ml4gw.real.numpy(), atol=1e-2
        )
        assert np.allclose(
            1e21 * hp_lal_data.imag, 1e21 * hp_ml4gw.imag.numpy(), atol=1e-3
        )
        assert np.allclose(
            1e21 * hc_lal_data.real, 1e21 * hc_ml4gw.real.numpy(), atol=1e-3
        )
        assert np.allclose(
            1e21 * hc_lal_data.imag, 1e21 * hc_ml4gw.imag.numpy(), atol=1e-3
        )
        # assert False
