import lal
import lalsimulation
import numpy as np
import pytest
import torch
from astropy import units as u

import ml4gw.waveforms as waveforms
from ml4gw.waveforms.conversion import (
    chirp_mass_and_mass_ratio_to_components,
)

TARGET_OVERLAP = 1 - 1e-7


@pytest.fixture(params=[20])
def f_ref(request):
    return request.param


@pytest.fixture(params=[2048])
def sample_rate(request):
    return request.param


# name, chirp_mass, mass_ratio, chi1, chi2, distance, phase, theta_jn
ALIGNED_TEST_CASES = [
    ("equal_mass_zero_spin", 26.12, 0.99, 0.0, 0.0, 100.0, 0.0, 0.0),
    ("low_q_limit", 15.0, 1 / 20.0, 0.0, 0.0, 100.0, 0.0, 0.4),
    ("max_spin_aligned", 30.0, 0.8, 0.99, 0.99, 150.0, 0.8, 0.5),
    ("max_spin_anti_aligned", 30.0, 0.8, -0.99, -0.99, 150.0, 0.8, 0.5),
    ("low_mass_bns", 1.21, 0.9, 0.05, 0.05, 40.0, 0.0, 0.0),
    ("high_mass_bbh", 70.0, 0.9, 0.5, 0.5, 500.0, 1.5, 0.8),
]


# name, chirp_mass, mass_ratio, chi1, chi2, distance, phase, theta_jn
PRECESSING_TEST_CASES = [
    (
        "max_chi_p",
        25.0,
        0.7,
        [0.99, 0.0, 0.0],
        [0.0, 0.0, 0.0],
        100.0,
        0.0,
        0.5,
    ),
    (
        "edge_on_precession",
        30.0,
        0.5,
        [0.5, 0.5, 0.0],
        [0.0, 0.0, 0.0],
        100.0,
        0.0,
        np.pi / 2,
    ),
    (
        "anti_aligned_precession",
        40.0,
        0.25,
        [0.8, 0.0, -0.4],
        [0.0, 0.0, -0.4],
        200.0,
        0.0,
        0.7,
    ),
    (
        "generic_orientation",
        20.0,
        0.8,
        [0.3, -0.2, 0.4],
        [0.1, 0.5, -0.2],
        500.0,
        1.2,
        0.4,
    ),
]


def compute_match(h1, h2):
    inner_prod = torch.sum(torch.conj(h1) * h2)
    norm1 = torch.sqrt(torch.sum(torch.conj(h1) * h1))
    norm2 = torch.sqrt(torch.sum(torch.conj(h2) * h2))
    return (inner_prod.abs() / (norm1 * norm2)).real


@pytest.mark.parametrize(
    "name, chirp_mass, mass_ratio, chi1, chi2, distance, phase, theta_jn",
    ALIGNED_TEST_CASES,
)
def test_taylor_f2(
    name,
    chirp_mass,
    mass_ratio,
    chi1,
    chi2,
    distance,
    phase,
    theta_jn,
    f_ref,
    sample_rate,
):
    chirp_mass = torch.tensor([chirp_mass], dtype=torch.float64)
    mass_ratio = torch.tensor([mass_ratio], dtype=torch.float64)
    chi1 = torch.tensor([chi1], dtype=torch.float64)
    chi2 = torch.tensor([chi2], dtype=torch.float64)
    distance = torch.tensor([distance], dtype=torch.float64)
    phase = torch.tensor([phase], dtype=torch.float64)
    theta_jn = torch.tensor([theta_jn], dtype=torch.float64)

    # Test that a difference in the length of a
    # parameter tensor raises an error
    with pytest.raises(ValueError, match="Tensors must have same batch size"):
        torch_freqs = torch.arange(100)
        waveforms.TaylorF2()(
            torch_freqs,
            chirp_mass[1:],
            mass_ratio,
            chi1,
            chi2,
            distance,
            phase,
            theta_jn,
            f_ref,
        )

    mass_1, mass_2 = chirp_mass_and_mass_ratio_to_components(
        chirp_mass, mass_ratio
    )

    # construct lalinference params
    params = {
        "m1": mass_1.item() * lal.MSUN_SI,
        "m2": mass_2.item() * lal.MSUN_SI,
        "S1x": 0,
        "S1y": 0,
        "S1z": chi1.item(),
        "S2x": 0,
        "S2y": 0,
        "S2z": chi2.item(),
        "distance": (distance.item() * u.Mpc).to("m").value,
        "inclination": theta_jn.item(),
        "phiRef": phase.item(),
        "longAscNodes": 0.0,
        "eccentricity": 0.0,
        "meanPerAno": 0.0,
        "deltaF": 1.0 / sample_rate,
        "f_min": 20,
        "f_ref": f_ref,
        "f_max": 300,
        "approximant": lalsimulation.TaylorF2,
        "LALpars": lal.CreateDict(),
    }
    hp_lal, hc_lal = lalsimulation.SimInspiralChooseFDWaveform(**params)

    # reconstruct frequencies generated by
    # lal and filter based on fmin and fmax
    lal_freqs = np.array(
        [hp_lal.f0 + ii * hp_lal.deltaF for ii in range(len(hp_lal.data.data))]
    )

    lal_mask = (lal_freqs > params["f_min"]) & (lal_freqs < params["f_max"])

    lal_freqs = lal_freqs[lal_mask]
    torch_freqs = torch.tensor(lal_freqs, dtype=torch.float64)

    # generate waveforms using ml4gw
    hc_ml4gw, hp_ml4gw = waveforms.TaylorF2()(
        torch_freqs,
        chirp_mass,
        mass_ratio,
        chi1,
        chi2,
        distance,
        phase,
        theta_jn,
        f_ref,
    )

    hc_ml4gw = hc_ml4gw[0]
    hp_ml4gw = hp_ml4gw[0]

    hp_lal_data = hp_lal.data.data[lal_mask]
    hc_lal_data = hc_lal.data.data[lal_mask]

    # ensure no nans
    assert not torch.any(torch.isnan(hc_ml4gw))
    assert not torch.any(torch.isnan(hp_ml4gw))

    assert compute_match(hp_ml4gw, torch.tensor(hp_lal_data)) > TARGET_OVERLAP
    assert compute_match(hc_ml4gw, torch.tensor(hc_lal_data)) > TARGET_OVERLAP

    # taylor f2 is symmetric w.r.t m1 --> m2 flip.
    # so test that the waveforms are the same when m1 and m2
    # (and corresponding chi1, chi2 are flipped)
    # are flipped this can be done by flipping mass ratio
    hc_ml4gw, hp_ml4gw = waveforms.TaylorF2()(
        torch_freqs,
        chirp_mass,
        1 / mass_ratio,
        chi2,
        chi1,
        distance,
        phase,
        theta_jn,
        f_ref,
    )

    hc_ml4gw = hc_ml4gw[0]
    hp_ml4gw = hp_ml4gw[0]

    assert compute_match(hp_ml4gw, torch.tensor(hp_lal_data)) > TARGET_OVERLAP
    assert compute_match(hc_ml4gw, torch.tensor(hc_lal_data)) > TARGET_OVERLAP


@pytest.mark.parametrize(
    "name, chirp_mass, mass_ratio, chi1, chi2, distance, theta_jn, phase",
    ALIGNED_TEST_CASES,
)
def test_phenom_d(
    name,
    chirp_mass,
    mass_ratio,
    chi1,
    chi2,
    distance,
    phase,
    theta_jn,
    sample_rate,
    f_ref,
):
    chirp_mass = torch.tensor([chirp_mass], dtype=torch.float64)
    mass_ratio = torch.tensor([mass_ratio], dtype=torch.float64)
    chi1 = torch.tensor([chi1], dtype=torch.float64)
    chi2 = torch.tensor([chi2], dtype=torch.float64)
    distance = torch.tensor([distance], dtype=torch.float64)
    theta_jn = torch.tensor([theta_jn], dtype=torch.float64)
    phase = torch.tensor([phase], dtype=torch.float64)

    # Test that a difference in the length of a
    # parameter tensor raises an error
    with pytest.raises(ValueError, match="Tensors must have same batch size"):
        torch_freqs = torch.arange(100)
        waveforms.IMRPhenomD()(
            torch_freqs,
            chirp_mass[1:],
            mass_ratio,
            chi1,
            chi2,
            distance,
            phase,
            theta_jn,
            f_ref,
        )

    mass_1, mass_2 = chirp_mass_and_mass_ratio_to_components(
        chirp_mass, mass_ratio
    )
    # construct lalinference params
    params = {
        "m1": mass_1.item() * lal.MSUN_SI,
        "m2": mass_2.item() * lal.MSUN_SI,
        "S1x": 0,
        "S1y": 0,
        "S1z": chi1.item(),
        "S2x": 0,
        "S2y": 0,
        "S2z": chi2.item(),
        "distance": (distance.item() * u.Mpc).to("m").value,
        "inclination": theta_jn.item(),
        "phiRef": phase.item(),
        "longAscNodes": 0.0,
        "eccentricity": 0.0,
        "meanPerAno": 0.0,
        "deltaF": 1.0 / sample_rate,
        "f_min": 20,
        "f_ref": f_ref,
        "f_max": 300,
        "approximant": lalsimulation.IMRPhenomD,
        "LALpars": lal.CreateDict(),
    }
    hp_lal, hc_lal = lalsimulation.SimInspiralChooseFDWaveform(**params)

    # reconstruct frequencies generated by
    # lal and filter based on fmin and fmax
    lal_freqs = np.array(
        [hp_lal.f0 + ii * hp_lal.deltaF for ii in range(len(hp_lal.data.data))]
    )

    lal_mask = (lal_freqs > params["f_min"]) & (lal_freqs < params["f_max"])

    lal_freqs = lal_freqs[lal_mask]
    torch_freqs = torch.tensor(lal_freqs, dtype=torch.float64)

    # generate waveforms using ml4gw
    hc_ml4gw, hp_ml4gw = waveforms.IMRPhenomD()(
        torch_freqs,
        chirp_mass,
        mass_ratio,
        chi1,
        chi2,
        distance,
        phase,
        theta_jn,
        f_ref,
    )

    hc_ml4gw = hc_ml4gw[0]
    hp_ml4gw = hp_ml4gw[0]

    hp_lal_data = hp_lal.data.data[lal_mask]
    hc_lal_data = hc_lal.data.data[lal_mask]

    assert not torch.any(torch.isnan(hc_ml4gw))
    assert not torch.any(torch.isnan(hp_ml4gw))

    assert compute_match(hp_ml4gw, torch.tensor(hp_lal_data)) > TARGET_OVERLAP
    assert compute_match(hc_ml4gw, torch.tensor(hc_lal_data)) > TARGET_OVERLAP


@pytest.mark.parametrize(
    "name, chirp_mass, mass_ratio, chi1, chi2, distance, phase, theta_jn",
    PRECESSING_TEST_CASES,
)
def test_phenom_p(
    name,
    chirp_mass,
    mass_ratio,
    chi1,
    chi2,
    distance,
    phase,
    theta_jn,
    sample_rate,
    f_ref,
):
    chirp_mass = torch.tensor([chirp_mass], dtype=torch.float64)
    mass_ratio = torch.tensor([mass_ratio], dtype=torch.float64)
    chi1x, chi1y, chi1z = [torch.tensor(c, dtype=torch.float64) for c in chi1]
    chi2x, chi2y, chi2z = [torch.tensor(c, dtype=torch.float64) for c in chi2]
    distance = torch.tensor([distance], dtype=torch.float64)
    theta_jn = torch.tensor([theta_jn], dtype=torch.float64)
    phase = torch.tensor([phase], dtype=torch.float64)

    mass_1, mass_2 = chirp_mass_and_mass_ratio_to_components(
        chirp_mass, mass_ratio
    )

    # Test `tc = None`
    torch_freqs = torch.arange(100)
    hc_ml4gw, hp_ml4gw = waveforms.IMRPhenomPv2()(
        torch_freqs,
        chirp_mass,
        mass_ratio,
        chi1x,
        chi1y,
        chi1z,
        chi2x,
        chi2y,
        chi2z,
        distance,
        phase,
        theta_jn,
        f_ref,
        tc=None,
    )

    tc = 0.0

    # construct lalinference params
    params = {
        "m1": mass_1.item() * lal.MSUN_SI,
        "m2": mass_2.item() * lal.MSUN_SI,
        "S1x": chi1x.item(),
        "S1y": chi1y.item(),
        "S1z": chi1z.item(),
        "S2x": chi2x.item(),
        "S2y": chi2y.item(),
        "S2z": chi2z.item(),
        "distance": (distance.item() * u.Mpc).to("m").value,
        "inclination": theta_jn.item(),
        "phiRef": phase.item(),
        "longAscNodes": 0.0,
        "eccentricity": 0.0,
        "meanPerAno": 0.0,
        "deltaF": 1.0 / sample_rate,
        "f_min": 20.0,
        "f_ref": f_ref,
        "f_max": 300,
        "approximant": lalsimulation.IMRPhenomPv2,
        "LALpars": lal.CreateDict(),
    }
    hp_lal, hc_lal = lalsimulation.SimInspiralChooseFDWaveform(**params)

    # reconstruct frequencies generated by
    # lal and filter based on fmin and fmax
    lal_freqs = np.array(
        [hp_lal.f0 + ii * hp_lal.deltaF for ii in range(len(hp_lal.data.data))]
    )

    lal_mask = (lal_freqs > params["f_min"]) & (lal_freqs < params["f_max"])

    lal_freqs = lal_freqs[lal_mask]
    torch_freqs = torch.tensor(lal_freqs, dtype=torch.float64)

    hc_ml4gw, hp_ml4gw = waveforms.IMRPhenomPv2()(
        torch_freqs,
        chirp_mass,
        mass_ratio,
        chi1x,
        chi1y,
        chi1z,
        chi2x,
        chi2y,
        chi2z,
        distance,
        phase,
        theta_jn,
        f_ref,
        torch.tensor([tc]),
    )

    hp_ml4gw = hp_ml4gw[0]
    hc_ml4gw = hc_ml4gw[0]

    hp_lal_data = hp_lal.data.data[lal_mask]
    hc_lal_data = hc_lal.data.data[lal_mask]

    assert compute_match(hp_ml4gw, torch.tensor(hp_lal_data)) > TARGET_OVERLAP
    assert compute_match(hc_ml4gw, torch.tensor(hc_lal_data)) > TARGET_OVERLAP

    # test batched outputs works as expected
    hc_ml4gw, hp_ml4gw = waveforms.IMRPhenomPv2()(
        torch_freqs,
        chirp_mass.repeat(5),
        mass_ratio.repeat(5),
        chi1x.repeat(5),
        chi1y.repeat(5),
        chi1z.repeat(5),
        chi2x.repeat(5),
        chi2y.repeat(5),
        chi2z.repeat(5),
        distance.repeat(5),
        phase.repeat(5),
        theta_jn.repeat(5),
        f_ref,
        torch.tensor([tc]).repeat(5),
    )

    # check batch against lal
    assert (
        compute_match(hp_ml4gw[0], torch.tensor(hp_lal_data)) > TARGET_OVERLAP
    )
    assert (
        compute_match(hc_ml4gw[0], torch.tensor(hc_lal_data)) > TARGET_OVERLAP
    )

    # check batch against each other
    for i in range(4):
        assert compute_match(hp_ml4gw[i], hp_ml4gw[0]) > TARGET_OVERLAP
        assert compute_match(hc_ml4gw[i], hc_ml4gw[0]) > TARGET_OVERLAP

    with pytest.raises(ValueError, match=r"Invalid mode s=-2, l=2, m=3*"):
        waveforms.IMRPhenomPv2().SpinWeightedY(0, 0, -2, 2, 3)
